### ISSUE TITLE
siri_ride_stops/list not working

### ISSUE THREAD

**Issue by zamirD123** [hasadna/open-bus-stride-client#8]
Hi @OriHoch, when trying to use `siri_ride_stops/list` I get an empty list. This auccures in the "Getting all arrivals to all stops of a given line in a given day" notebook but also when i'm just experimenting with the API

**Comment by OriHoch** [comment]
@zamirD123 thanks for the bug report!
I fixed it

**Comment by zamirD123** [comment]
Thanks! super quick!!
